name: ebetz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  google_fonts: ^6.2.1
  animated_notch_bottom_bar: ^1.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^11.3.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flashy_tab_bar2: ^0.0.10
  curved_labeled_navigation_bar: ^2.0.5
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  url_launcher: ^6.1.7
  google_sign_in: ^6.1.5
  flutter_facebook_auth: 7.1.1

dependency_overrides:
  http: ^1.0.0
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appicon.png"


flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/home_images/
      - assets/cutout/
